# Generated by Django 5.2.11 on 2026-08-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='business',
            field=models.ForeignKey(blank=True, help_text='اگر خالی باشد، این بنر سراسری است و برای همه\u200cی آرایشگاه\u200cها نمایش داده می\u200cشود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='business.business', verbose_name='کسب\u200cوکار'),
        ),
    ]
