# Generated by Django 5.2.11 on 2026-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('male_salon', 'آرایشگاه مردانه'), ('female_salon', 'آرایشگاه زنانه')], max_length=20, verbose_name='نوع کسب\u200cوکار'),
        ),
    ]
