# Generated by Django 5.2.11 on 2026-08-23 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment_created', 'ثبت نوبت جدید'), ('appointment_confirmed', 'تایید نوبت'), ('appointment_canceled', 'لغو نوبت'), ('appointment_reminder', 'یادآوری نوبت'), ('new_appointment', 'نوبت جدید (برای صاحب آرایشگاه)'), ('appointment_canceled_by_customer', 'لغو نوبت توسط مشتری'), ('new_package_review', 'نظر جدید روی پکیج'), ('subscription_trial_ending', 'پایان نزدیک دوره\u200cی آزمایشی'), ('subscription_expired', 'پایان اشتراک'), ('general', 'عمومی')], default='general', max_length=40, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده\u200cشده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.appointment', verbose_name='نوبت مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type', 'created_at'], name='notificatio_user_id_ef3643_idx')],
            },
        ),
    ]
